import 'package:get/get.dart';

class WorldLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello': 'Hello',
          'desk': 'Desk',
          'live':
              'Live as if you were to die tomorrow. Learn as if you were to live forever.',
          'student': 'Students',
          'parents': 'Parents',
          'activitiescalender': 'Activities Calender',
          'holiday': 'Holiday',
          'festival': 'Festival',
          'clelebration': 'Celebration',
          'exam': 'Exam',
          'viewall': 'View All',
          'message': 'Message',
          'parent': 'Parent',
          'email': 'email',
          'education': 'education',
          'profession': 'profession',
          'classes': 'Classes',
          'events': 'Events',
          'timetable': 'Time Table',
          'teachers': 'Teachers',
          'subjects': 'Subjects',
          'subject': 'Subject',
          'examname': 'Exam Name',
          'grade': 'Grade',
          'obser': 'Observation',
          'tests': 'Tests',
          'grades': 'Grades',
          'evaluation': 'Evaluation',
          'attendence': 'Attendence',
          'studatte': "Student Attendence",
          'circular': 'Circular',
          'circulardetail': 'Circular Details',
          'settings': 'Settings',
          'enclass': 'Entolled Classes',
          'subject': 'Subject',
          'iotc': 'Incharge of the class',
          'fch': 'Family care hours',
          'techerdetail': 'Teacher Detail',
          'mo': 'Mo',
          'tu': 'Tu',
          'we': 'We',
          'th': 'Th',
          'fr': 'Fr',
          'class': 'Class',
          'lpn': 'License plate number',
          'cs': 'Class Start',
          'ce': 'Class End',
          'noad': 'Number of Absent days',
          'nopd': 'Number of Present days',
          'noattday': 'Number of Attendance days',
          'date': 'Date',
          'title': 'Title',
          'professor': 'Professor',
          'testdetail': 'Details of exam/work',
          'studentdetail': 'Student Details',
          'bloodgrp': 'Blood Group',
          'dob': 'Date of Birth',
          'address': 'Address',
          'streetaddress': 'Street Address',
          'city': 'City',
          'pincode': 'Pincode',
          'country': 'Country',
          'schooldetail': 'School Detail',
          'doj': 'Date of Joining',
          'rollno': 'Roll No',
          'parentsdetail': 'Father\'s Details',
          'parentsdetail2': 'Mother\'s Details',
          'pname': 'Father Name',
          'pname2': 'Mother Name',
          'pemail': 'Email Address',
          'mobile': 'Phone Number',
          'gender': 'Gender',
          'parentpro': 'Parent Profession',
          'subjectdetail': 'Subjects Details',
          'subjectcode': 'Subject Code',
          'faculty': 'Faculty',
          'nameofthebook': 'Name Of The Book',
          'login': 'Login',
          'Every': 'Everything Your School Needs In One Place',
          'user': 'User',
          'password': ' Password',
          'rember': 'Remember Me',
          'forgot': ' forgot  password?',
          'singin': ' SIGN IN',
          'optimize':
              'Optimize School Administration With  Unparalleled Flexibility',
          'trans': 'Transportation',
          'vname': 'Vehicle Name',
          'dname': 'Driver Name',
          'dnumber': 'Driver\'s Number',
          'rrate': 'Route of Rate',
          'vroute': 'Vehicle Route',
          'stu': 'Student',
          'prent': 'Parent',
          'selectrole': 'Select Role',
          'logout': 'Logout',
          'comment': 'Comments',
          'le': 'LIST EMPTY',
          'hour': 'Hours',
          '1st': '1st',
          '2nd': '2nd',
          '3rd': '3rd',
          'final': 'Final',
          'ER': 'Evaluation Report',
          'comment': 'Comments',
          'assistant': "assistant",
          'eventsCalendar': 'Events Calendar',

          //send new message screen strings
          'sendButton': 'Enviar',
          'affText': 'Amorío',
          'tryAgain' : 'try again',

          //no evolution
          'ObservationEmpty':
              'There are no observations of any subject in this Assessment',
          "workingHours": "Working Hours",
          'singalClass': 'class',
          'phoneNumber': 'Phone Number',
          'emailAdd': 'Email Address',
          'noStudentFound': 'There are no results.',
          'searchInList': 'search',
          'noTransport': 'Do not use this service',
          'groupName': 'Group',
          'pTitle': 'Parents',
          'eTitle': 'Academic training',
          'mTitle': 'Message Details',

          //send message to teacher
          'sendNewTitle': 'Send New Message',
          'sendTitle': 'Send',
          'attachTitle': 'Attachment',
          'msgTitle': 'Message',
          'afTitle': 'Affair',
          'selectTitle': 'Select Teacher',
          'chooseTitle': 'Choose File',

          //assistant module
          'noData' : 'Assistant Does not have any assign class.',
          'cmn': 'Communications',
          'send_cmn' : 'Send Communications',
          'cmn_det': 'Communication Details',
          'cmn_report' : 'Report Details',
          'option1': 'Common Message',
          'option2': 'Student Report',
          'reportOption' : 'Report',
          'asDate': 'Date',
          'asMsg': 'Message',
          'asSub': 'Subject',
          'asRpt': 'Report Of The Day',
          'asHrs': 'Hours',
          'asCmt': 'Comments',
          'asWork': 'Working day',
          'asNew': 'New Communication',
          'asNew2' : 'New Report',
          'asPrtV': 'Parent View',
          'asAtch': 'Attachment',
          'asChoose': 'Choose File',
          'asSd': 'Send',
          'asClass': 'Select Class',
          'asParent': 'Select Parent',
          'asAll': 'All Parents',
          'asSelect': 'Selected Students',
          'asStd': 'Select Student',
          'asChildDet': 'Children\'s Details',
          'asPareDet': 'Parent\'s Details',
          'asChild': 'Child\'s',
          'asList': 'List is Empty',
          'asCmnReport': 'Common Report Count',
          'asStdReport': 'Student Report Count',
          'asNoStd' : 'There is no student in class.',
          'asNoSlot' : 'There is no slot available today.',
          'asCancel' : 'Cancel',
          'asClassTitle' : 'Classes',
          'asPadre' : 'Parent Name',
          'allPadre' : 'All Parents',
          'asSendName' : 'From',
          'selectAssistant' : 'Select Assistant',
          'sendOption' : 'Send',
          'receiveOption' : 'Received',
          'asMessageSent' : 'Message Sent Successfully',
          'asSubject' : 'Subject Compulsory',

          //can not open attachment
          'canNot': 'Can not Open Document',
          'yearInSpan' : 'Years',

          //utils
          'loginDone': 'login successfully',

          //drawer option
          'drawerOption1' : 'Desk',
          'drawerOption2' : 'Parents',
          'drawerOption3' : 'Class Name',
          'drawerOption4' : 'Events',
          'drawerOption5' : 'Circulars',
          'drawerOption6' : 'Message',
          'drawerOption7' : 'Students',

          //sub menu option
          'subMenuDrawer1' : 'Time Table',
          'subMenuDrawer2' : 'Teachers',
          'subMenuDrawer3' : 'Students',
          'subMenuDrawer4' : 'Subject',
          'subMenuDrawer5' : 'Exam',
          'subMenuDrawer6' : 'Marks',
          'subMenuDrawer7' : 'Evaluation',
          'subMenuDrawer8' : 'Attendance',
          'subMenuDrawer9' : 'Tranportation',

          //Assistant Module Strings
          'as1' : 'Children\'s',
          'menu1' : 'Reports',
          'menu2' : 'Send message to assistant',

          //log out dialog option
          'sure' : 'Confirm logout ?',
          'positiveButton' : 'Yes',
          'negativeButton' : 'No',


          'logOut' : 'successfully logout',
           'sessionExpired' : 'Session Expired,Please Login Again.',

          //send message successfully
          'parentSendMessage' : 'Communication sent successfully',
          'assistantToParent' : 'Report sent successfully',
        },
        'es_ES': {
          'hello': 'Hola',
          'desk': 'Escritorio',
          'live':
              'Sistema de Gestión Docente de la Comunidad Educativa del Colegio Atenea',
          'student': 'Alumnos',
          'parents': 'Padres',
          'activitiescalender': 'Calendario de actividades',
          'holiday': 'Vacaciones',
          'festival': 'Festivo',
          'eventsCalendar': 'Calendario de eventos',
          'clelebration': 'Celebraciones',
          'exam': 'Examen',
          'viewall': 'Ver todo',
          'message': 'Comunicaciones',
          'parent': 'Padre',
          'email': 'Email',
          'education': 'Educacion',
          'profession': 'Profesion',
          'classes': 'Clases',
          'events': 'Eventos',
          'timetable': 'Horario',
          'teachers': 'Profesores',
          'subjects': 'Asignaturas',
          'subject': 'Asignatura',
          'examname': 'Examen/Trabajo',
          'tests': 'Exámenes/Trabajos',
          'grades': 'Notas',
          'obser': 'Observaciones',
          'grade': 'Nota',
          'evaluation': 'Evaluaciones',
          'attendence': 'Ausencias',
          'studatte': 'Ausencias del alumno',
          'circular': 'Circulares',
          'circulardetail': 'Detalles de la Circular',
          'settings': 'Configuración',
          'enclass': 'Classes',
          'subject': 'Asignatura',
          'iotc': 'Tutoría',
          'fch': 'Horario de atención a la familia',
          'techerdetail': 'Detalles del profesor',
          'mo': 'Lu',
          'tu': 'Ma',
          'we': 'Mi',
          'th': 'Ju',
          'fr': 'Vi',
          'class': 'Clases',
          'lpn': 'Nº matrícula',
          'cs': 'Inicio de curso',
          'ce': ' Finalización del curso',
          'noad': ' Total días ausentes',
          'nopd': 'Total días presentes',
          'noattday': 'Nºdías de ausencias',
          'date': 'Fecha',
          'title': 'Examen/Trabajo',
          'professor': 'Profesor',
          'testdetail': 'Detalles del examen/trabajo',
          'studentdetail': 'Detalles del Alumno',
          'bloodgrp': 'Grupo sanguíneo',
          'dob': ' Fecha de nacimiento',
          'address': 'Dirección',
          'streetaddress': 'Dirección',
          'city': '  Localidad',
          'pincode': 'Código Postal',
          'country': '  País',
          'schooldetail': 'Detalle de la matrícula',
          'doj': 'Fecha de matrícula',
          'rollno': ' Nº matrícula',
          'parentsdetail': 'Detalles del Padre',
          'parentsdetail2': 'Detalles de la Madre',
          'pname': ' Nombre del Padre',
          'pname2': ' Nombre del Madre',
          'pemail': 'Email',
          'mobile': 'Móvil',
          'gender': 'Género',
          'parentpro': 'Profesión',
          'subjectdetail': 'Detalle de la asignatura',
          'subjectcode': 'Código asignatura',
          'faculty': 'Profesor',
          'nameofthebook': 'Nombre del libro',
          'login': 'Entrar',
          'Every': 'Todo lo que tu escuela necesita en un solo lugar',
          'user': 'Usuario',
          'password': ' Contraseña',
          'rember': 'Recordarme',
          'forgot': ' ¿ Olvidaste tu contraseña?',
          'singin': ' ENTRAR',
          'optimize':
              'Optimice la administración escolar con una flexibilidad sin igual',
          'trans': 'Transporte',
          'vname': 'Empresa',
          'dname': 'Nombre del conductor',
          'dnumber': 'Teléfono del conductor',
          'rrate': ' Precio de la ruta',
          'vroute': 'Ruta',
          'stu': 'Alumno',
          'prent': 'Padre',
          'selectrole': 'Seleccionar perfil',
          'logout': 'Salir',
          'comment': 'Comentarios',
          'le': 'LISTA VACÍA',
          'hour': 'Hora',
          '1st': '1ª',
          '2nd': '2ª',
          '3rd': '3ª',
          'final': 'Final',
          'ER': 'Informe de Evaluacion',
          'comment': 'Comentarios',
          'assistant': "Asistente",

          'ObservationEmpty':
              'No hay observaciones de ninguna asignatura en esta Evaluación.',
          "workingHours": "Horas Laborales",
          'singalClass': 'Clase',
          'phoneNumber': 'Número de teléfono',
          'emailAdd': 'Dirección de correo electrónico',
          'noStudentFound': 'no hay resultados',
          'searchInList': 'buscar',
          'noTransport': 'No utiliza este servicio',
          'groupName': 'Grupo',
          'pTitle': 'Padres',
          'eTitle': 'Formación académica',
          'mTitle': 'Detalles del mensaje',
          'tryAgain' : 'intentar otra vez',

          //send message to teacher
          'sendNewTitle': 'Enviar mensaje nuevo',
          'sendTitle': 'enviar',
          'attachTitle': 'Adjunto',
          'msgTitle': 'Mensaje',
          'afTitle': 'Asunto',
          'selectTitle': 'Seleccionar profesor',
          'chooseTitle': 'Elija el archivo',

          //assistant module
          'noData' : 'Asistente No tiene ninguna clase asignada.',
          'cmn': 'Comunicaciones e Informes',
          'send_cmn' : 'Enviar Comunicaciones',
          'cmn_det': 'Detalle de la comunicación',
          'cmn_report' : 'Detalle del informe' ,
          'option1': 'Comunicaciones',
          'option2': 'Informes de los Petites',
          'reportOption' : 'Informes',
          'asDate': 'Fecha',
          'asMsg': 'Mensaje',
          'asSub': 'Asunto',
          'asRpt': 'Informe del día',
          'asHrs': 'Horas',
          'asCmt': 'Comentarios',
          'asWork': 'Día de trabajo',
          'asNew': 'Nueva comunicación',
          'asNew2' : 'Nuevo informe',
          'asPrtV': 'Mostrar al Padre',
          'asAtch': 'Adjunto',
          'asChoose': 'Elija el archivo',
          'asSd': 'Enviar',
          'asClass': 'Seleccionar clase',
          'asParent': 'Seleccionar padre',
          'asAll': 'Todos los padres',
          'asSelect': 'Petites Seleccionados',
          'asStd': 'Seleccionar Petites',
          'asChildDet': 'Detalles de los niños',
          'asPareDet': 'Detalles de los padres',
          'asChild': 'Niños',
          'asList': 'La lista esta vacía',
          'asCancel' : 'Cancelar',
          'asClassTitle' : 'Clases',
          'asCmnReport': 'Recuento de informes comunes',
          'asStdReport': 'Recuento de informes de estudiantes',
          'canNot': 'No se puede abrir el documento.',
          'asNoStd' : 'No hay ningún alumno en clase.',
          'asNoSlot' : 'No hay sesiones disponibles en el horario de hoy',
          'asPadre' : 'Nombre',
          'allPadre' : 'Todos los padres',
          'yearInSpan' : 'años',
          'asSendName' : 'De',
          'selectAssistant' : 'Seleccionar asistente',
          'sendOption' : 'Enviadas',
          'receiveOption' : 'Recibidas',
          'asMessageSent' : 'Mensaje enviado con éxito',
          'asSubject' : 'Materia Obligatoria',


          //utils
          'loginDone': 'Inicio de sesión correcto',
          'logOut' : 'Cierre de sesión correcto',

          //drawer option
          'drawerOption1' : 'Escritorio',
          'drawerOption2' : 'Padres',
          'drawerOption3' : 'Clase',
          'drawerOption4' : 'Eventos',
          'drawerOption5' : 'Circulares',
          'drawerOption6' : 'Comunicaciones',
          'drawerOption7' : 'Alumnos',


          //sub menu option
          'subMenuDrawer1' : 'Horario',
          'subMenuDrawer2' : 'Profesores',
          'subMenuDrawer3' : 'Alumnos',
          'subMenuDrawer4' : 'Asignaturas',
          'subMenuDrawer5' : 'Exámenes/Trabajos',
          'subMenuDrawer6' : 'Notas',
          'subMenuDrawer7' : 'Evaluaciones',
          'subMenuDrawer8' : 'Ausencias',
          'subMenuDrawer9' : 'Transporte',

          //
          'as1' : 'Niños',
          'as2' : '',
          'menu1' : 'Informes',
          'menu2' : 'Enviar mensaje a la Asistente',

          //log out dialog
          'sure' : 'Confirmar cierre de sesión?',
          'positiveButton' : 'Si',
          'negativeButton' : 'No',

          'sessionExpired' : 'La sesión expiró, inicie sesión nuevamente.',

          //send message successfully
           'parentSendMessage' : 'Comunicación enviada correctamente',
           'assistantToParent' : 'Informe enviado correctamente',
        },

        //add more language here
      };
}
